dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2021-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: T4yYxHKjcVWuNZdEteMC9vuh+CReBwVB5JPJcZIoY+fcpkndC0jaJ33TeRcca7OaIksIW+HmkO9E92cZYaSO+NtxMYqP2qVykgT+G/CHZdf4GFByUH54o8IHZ/yxqFYAv2sxUOnDs/Dq/+07rBbOfkgpZvveHJCQS2s37z8h5qd2fNoTx5GxWq34Kggly6T10iMjE83louvLrNoRUJ09+FD84uasBP0fZflwI1hFSXUZUWnuOrdm5rgbHhgSTsKaEoA9tQ5OLCBt1VZkPVW37G1XdcaasHu3LD5u3aAd6xGIs2/75pBT0iENDzqxdgOUrVY0ZzrkkyGv409cr5v27YHIE6GP3BPWiPvBF0/VJtsX/2XoD36Dq3pWwv7XC1EXcw7pZbCVH6iFK5l2/Mj4HdEdbrGDIIIX7fqCqaVWGWsMU+Igox0ym7IYXrkPPqY0MINKZsj0bqtsISY/pJgMzfDE1JpyTX7EcEN2MnocJPixnv/wqI0z+PcGtm2XUYhRtIj3E0KJPbeVwQLxEeiCxnnG92ClI37trAJJ+D36pDpFLt28pgwJ6vXYO7dFqDlvXvRTekwU5swp2OUbaK0DvxHnaKdaWViK9fRPVlMFcHwwU5dZDM4ECUV2uHZiG+1zIWesg2gGf/3Bqvc3jCnow7RDPH42aIqhHj0Ke1WHxoE=
