---
- name: deploy application
  hosts: app
  tags: deploy-tag
  become: true
  vars:
    username: ubuntu
  handlers:
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ username }}/reddit'
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/{{ username }}/reddit'
      notify: reload puma
